// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1) {
  return window['go']['main']['App']['Convert'](arg1);
}

export function Repetition(arg1) {
  return window['go']['main']['App']['Repetition'](arg1);
}

export function Reverse(arg1) {
  return window['go']['main']['App']['Reverse'](arg1);
}

export function Validate(arg1) {
  return window['go']['main']['App']['Validate'](arg1);
}
