// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckString(arg1:string):Promise<string>;

export function Reverse(arg1:string):Promise<string>;
