// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Reverse(arg1:string):Promise<string>;

export function Validate(arg1:string):Promise<string>;
